name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build target platform
      run: mvn -B package --file target-platform/pom.xml
    - name: Build Kura Packages
      run: mvn -B package --file kura/pom.xml
    - name: Build Kura Examples
      run: mvn -B package --file kura/examples/pom.xml
    - name: Build Kura Distrib
      run: mvn -B package --file kura/distrib/pom.xml
